jre_table = {
    "0118": {
        "pl": {
            # "SHIPPED_FROM": {
            #     'x': 150,
            #     'y': 10,
            #     'keywords': [r'FROM'],
            #     'index': 0,
            #     'move_x': -50,
            #     'move_y': 0,
            #     # 'next_con': 90,
            #     # 'bottom_keywords': [r'SOLD', ],
            #     # 'bottom_keywords_index': 0,
            # },
            "CUSTOMER_ORDER_NUMBER": {
                'x': 200,
                'y': 30,
                'keywords': [r'CUSTOMER'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                # 'next_con': 90,
                # 'bottom_keywords': [r'SUB', ],
                # 'bottom_keywords_index': 0,
            },
            "Invo": {
                'x': 100,
                'y': 10,
                'keywords': [r'INVOICE'],
                'index': 0,
                'move_x': -10,
                'move_y': 10,
                # 'next_con': 90,
                # 'bottom_keywords': [r'SUB', ],
                # 'bottom_keywords_index': 0,
            },
            "CARTON": {
                'x': 100,
                'y': 10,
                'keywords': [r'CARTON'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "DIMENSION": {
                'x': 100,
                'y': 10,
                'keywords': [r'DIMENSION'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "GW": {
                'x': 50,
                'y': 10,
                'keywords': [r'GW'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "NW": {
                'x': 50,
                'y': 10,
                'keywords': [r'NW'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "PN": {
                'x': 80,
                'y': 10,
                'keywords': [r'NW'],
                'index': 0,
                'move_x': 30,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "CPN": {
                'x': 100,
                'y': 10,
                'keywords': [r'NW'],
                'index': 0,
                'move_x': 30,
                'move_y': 10,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "COO": {
                'x': 50,
                'y': 10,
                'keywords': [r'COO'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 16,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            "QTY": {
                'x': 60,
                'y': 10,
                'keywords': [r'QTY'],
                'index': 1,
                'move_x': -30,
                'move_y': 0,
                'next_con': 15,
                'bottom_keywords': [r'TOTAL', ],
                'bottom_keywords_index': 1,
            },
            # "CUSTOMER_NO": {
            #     'x': 100,
            #     'y': 10,
            #     'keywords': [r'CUSTOMER'],
            #     'index': 1,
            #     'move_x': -10,
            #     'move_y': 10,
            #     # 'next_con': 90,
            #     # 'bottom_keywords': [r'SUB', ],
            #     # 'bottom_keywords_index': 0,
            # },
        },
        "iv": {
            "Invo": {
                'x': 150,
                'y': 10,
                'keywords': [r'INVOICE'],
                'index': 1,
                'move_x': -10,
                'move_y': 10,
                # 'next_con': 90,
                # 'bottom_keywords': [r'SUB', ],
                # 'bottom_keywords_index': 0,
            },
            "QTY": {
                'x': 40,
                'y': 10,
                'keywords': [r'QUANTITY'],
                'index': 0,
                'move_x': 0,
                'move_y': 10,
                # 'next_con': 10,
                'bottom_keywords': [r'THIS', ],
                'bottom_keywords_index': 0,
            },
            "PN": {
                'x': 100,
                'y': 20,
                'keywords': [r'PN:'],
                'index': 0,
                'move_x': 0,
                'move_y': -10,
                # 'next_con': 10,
                # 'bottom_keywords': [r'THIS', ],
                # 'bottom_keywords_index': 0,
            },
            "DESCRIPTION": {
                'x': 100,
                'y': 20,
                'keywords': [r'PN:'],
                'index': 0,
                'move_x': 400,
                'move_y': -10,
                # 'next_con': 10,
                # 'bottom_keywords': [r'THIS', ],
                # 'bottom_keywords_index': 0,
            },
            "UNIT_PRICE": {
                'x': 100,
                'y': 20,
                'keywords': [r'PRICE'],
                'index': 0,
                'move_x': -30,
                'move_y': 10,
                # 'next_con': 10,
                # 'bottom_keywords': [r'THIS', ],
                # 'bottom_keywords_index': 0,
            },
            "EXTENDED_PRICE": {
                'x': 100,
                'y': 20,
                'keywords': [r'PRICE'],
                'index': 1,
                'move_x': -30,
                'move_y': 10,
                # 'next_con': 10,
                # 'bottom_keywords': [r'THIS', ],
                # 'bottom_keywords_index': 0,
            },
            "CUR": {
                'x': 25,
                'y': 15,
                'keywords': [r'CUR'],
                'index': 0,
                'move_x': -10,
                'move_y': 10,
                # 'next_con': 90,
                # 'bottom_keywords': [r'SUB', ],
                # 'bottom_keywords_index': 0,
            },
            # "CUSTOMER_ORDER_NUMBER": {
            #     'x': 100,
            #     'y': 20,
            #     'keywords': [r'CUSTOMER'],
            #     'index': 0,
            #     'move_x': 10,
            #     'move_y': 0,
            #     # 'next_con': 10,
            #     # 'bottom_keywords': [r'THIS', ],
            #     # 'bottom_keywords_index': 0,
            # },
        },

    },
    "0121": {
        "pl": {
            "Packing_List": {
                'x': 300,
                'y': 10,
                'keywords': [r'List'],
                'index': 1,
                'move_x': 20,
                'move_y': -10,

            },
            "CT": {
                'x': 50,
                'y': 80,
                'keywords': [r'CT#'],
                'index': 0,
                'move_x': -5,
                'move_y': 20,
                'next_con': 5,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
            "Comments": {
                'x': 50,
                'y': 17,
                'keywords': [r'Comments'],
                'index': 0,
                'move_x': -5,
                'move_y': 5,
                'next_con': 7,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
            "Part": {
                'x': 100,
                'y': 16,
                'keywords': [r'End'],
                'index': 0,
                'move_x': -10,
                'move_y': 5,
                'next_con': 5,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
            "Total_Quantity": {
                'x': 30,
                'y': 80,
                'keywords': [r'Quantity'],
                'index': 0,
                'move_x': -10,
                'move_y': 0,
                'next_con': 5,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
            "Country_of_Origin": {
                'x': 40,
                'y': 80,
                'keywords': [r'Country'],
                'index': 0,
                'move_x': 0,
                'move_y': 15,
                'next_con': 5,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
            "Net": {
                'x': 30,
                'y': 100,
                'keywords': [r'Gross'],
                'index': 0,
                'move_x': -40,
                'move_y': 20,
                'next_con': 40,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
                'isOnly': True
            },
            "Gross": {
                'x': 30,
                'y': 100,
                'keywords': [r'Gross'],
                'index': 0,
                'move_x': 10,
                'move_y': 20,
                'next_con': 40,
                'bottom_keywords': [r'AMS'],
                'bottom_keywords_index': 0,
            },
        },
        "iv": {
            "Invoice_Number": {
                'x': 150,
                'y': 10,
                'keywords': [r'Number'],
                'index': 0,
                'move_x': 10,
                'move_y': -10,
                # 'next_con': 25,
                # 'bottom_keywords': [r'SUB', ],
                # 'bottom_keywords_index': 0,
            },
            "Customer_PO": {
                'x': 150,
                'y': 10,
                'keywords': [r'Order'],
                'index': 0,
                'move_x': -30,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'Total:', ],
                'bottom_keywords_index': 0,
            },
            "Description": {
                'x': 150,
                'y': 10,
                'keywords': [r'Description'],
                'index': 0,
                'move_x': -30,
                'move_y': 40,
                'next_con': 10,
                'bottom_keywords': [r'Total:', ],
                'bottom_keywords_index': 0,
            },
            "Quantity": {
                'x': 100,
                'y': 10,
                'keywords': [r'Quantity'],
                'index': 0,
                'move_x': -30,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'Total:', ],
                'bottom_keywords_index': 0,
            },
            "Unit_Price": {
                'x': 100,
                'y': 10,
                'keywords': [r'Price'],
                'index': 0,
                'move_x': -30,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'Total:', ],
                'bottom_keywords_index': 0,
            },

        },

    },
    '0120': {
        'iv': {
            'PO': {
                'x': 150,
                'y': 10,
                'keywords': [r'PO#'],
                'index': 0,
                'move_x': -50,
                'move_y': 30,
                'next_con': 25,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'PN': {
                'x': 150,
                'y': 10,
                'keywords': [r'Description'],
                'index': 0,
                'move_x': -100,
                'move_y': 5,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'CUSTOM_PART': {
                'x': 150,
                'y': 10,
                'keywords': [r'Description'],
                'index': 0,
                'move_x': -100,
                'move_y': 15,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'DESCRIPTION': {
                'x': 200,
                'y': 10,
                'keywords': [r'Description'],
                'index': 0,
                'move_x': -100,
                'move_y': 25,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'QTY': {
                'x': 50,
                'y': 20,
                'keywords': [r'Description'],
                'index': 0,
                'move_x': 250,
                'move_y': -5,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'UNIT_PRICE': {
                'x': 50,
                'y': 20,
                'keywords': [r'Price'],
                'index': 0,
                'move_x': -10,
                'move_y': 30,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            'TOTAL_PRICE': {
                'x': 100,
                'y': 20,
                'keywords': [r'Price'],
                'index': 1,
                'move_x': -20,
                'move_y': 30,
                'next_con': 24,
                'bottom_keywords': [r'Total'],
                'bottom_keywords_index': 1,
            },
            "Invo": {
                'x': 200,
                'y': 20,
                'keywords': [r'CommercialInvoiceNumber:'],
                'index': 0,
                'move_x': 0,
                'move_y': -10,
                # 'next_con': 25,
                # 'bottom_keywords': [r'LeadTrackingNumber:'],
                # 'bottom_keywords_index': 0,
            },
        },
        'pl': {
            'CTN': {
                'x': 40,
                'y': 90,
                'keywords': [r'CTN'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 45,
                'bottom_keywords': [r'Summary'],
                'bottom_keywords_index': 0,
            },
            'PN': {
                'x': 150,
                'y': 10,
                'keywords': [r'Part#'],
                'index': 0,
                'move_x': -120,
                'move_y': 35,
                'next_con': 40,
                'bottom_keywords': [r'Summary'],
                'bottom_keywords_index': 0,
            },
            'C/O': {
                'x': 50,
                'y': 20,
                'keywords': [r'C/O'],
                'index': 1,
                'move_x': -10,
                'move_y': 35,
                'next_con': 40,
                'bottom_keywords': [r'Summary'],
                'bottom_keywords_index': 0,
            },
            'QTY': {
                'x': 70,
                'y': 20,
                'keywords': [r'Quantity'],
                'index': 0,
                'move_x': -30,
                'move_y': 35,
                'next_con': 40,
                'bottom_keywords': [r'Summary'],
                'bottom_keywords_index': 0,
            },
            'NW': {
                'x': 50,
                'y': 20,
                'keywords': [r'NetWeight'],
                'index': 1,
                'move_x': 0,
                'move_y': 10,
                'next_con': 40,
                'bottom_keywords': [r'SHIPMENTTOTALS'],
                'bottom_keywords_index': 0,
            },
            'GW': {
                'x': 50,
                'y': 20,
                'keywords': [r'GrossWeight'],
                'index': 0,
                'move_x': 0,
                'move_y': 10,
                'next_con': 40,
                'bottom_keywords': [r'SHIPMENTTOTALS'],
                'bottom_keywords_index': 0,
            },
            "Invo": {
                'x': 200,
                'y': 20,
                'keywords': [r'ShipmentID'],
                'index': 0,
                'move_x': 0,
                'move_y': -10,
                # 'next_con': 25,
                # 'bottom_keywords': [r'LeadTrackingNumber:'],
                # 'bottom_keywords_index': 0,
            },
        },
    },
    '0119': {
        'iv': {
            'PO': {
                'x': 80,
                'y': 10,
                'keywords': [r'P/O'],
                'index': 0,
                'move_x': -10,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'BRAND': {
                'x': 80,
                'y': 10,
                'keywords': [r'BRAND'],
                'index': 0,
                'move_x': -10,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'ITEM': {
                'x': 80,
                'y': 10,
                'keywords': [r'ITEM'],
                'index': 0,
                'move_x': -10,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'ORIGIN': {
                'x': 30,
                'y': 10,
                'keywords': [r'PLACE'],
                'index': 0,
                'move_x': -10,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'PART_NO': {
                'x': 80,
                'y': 10,
                'keywords': [r'PART'],
                'index': 1,
                'move_x': -10,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'QTY': {
                'x': 60,
                'y': 10,
                'keywords': [r'Q\'TY'],
                'index': 0,
                'move_x': -50,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'PRICE': {
                'x': 80,
                'y': 10,
                'keywords': [r'PRICE'],
                'index': 0,
                'move_x': -30,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'Invo': {
                'x': 100,
                'y': 20,
                'keywords': [r'NO:'],
                'index': 0,
                'move_x': 60,
                'move_y': -10,
                # 'next_con': 20,
                # 'bottom_keywords': [r'TOTAL:'],
                # 'bottom_keywords_index': 0,
            },
        },
        'pl': {
            'CN_NO': {
                'x': 50,
                'y': 10,
                'keywords': [r'C/N'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'ITEM': {
                'x': 150,
                'y': 10,
                'keywords': [r'ITEM'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'ORIGIN': {
                'x': 35,
                'y': 10,
                'keywords': [r'PLACE'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'QTY': {
                'x': 80,
                'y': 10,
                'keywords': [r'Q\'TY'],
                'index': 0,
                'move_x': -50,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'NW': {
                'x': 50,
                'y': 10,
                'keywords': [r'N.W.'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'GW': {
                'x': 50,
                'y': 10,
                'keywords': [r'G.W.'],
                'index': 0,
                'move_x': -5,
                'move_y': 30,
                'next_con': 10,
                'bottom_keywords': [r'TOTAL:'],
                'bottom_keywords_index': 0,
            },
            'INVOICE_NUMBER': {
                'x': 150,
                'y': 10,
                'keywords': [r'NO:'],
                'index': 0,
                'move_x': 10,
                'move_y': -5,
                # 'next_con': 10,
                # 'bottom_keywords': [r'TOTAL:'],
                # 'bottom_keywords_index': 0,
            },
        },
        'pak_x_tolerance': 0.1
    },
    '0112': {
        'inv_x_tolerance': 1,
        'pl': {},
        'iv': {
            'PO': {
                'x': 100,
                'y': 16,
                'keywords': [r'number'],
                'index': 0,
                'move_x': -50,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'SubTotal:'],
                'bottom_keywords_index': 0,
            },
            'DESCRIPTION': {
                'x': 230,
                'y': 16,
                'keywords': [r'DESCRIPTION'],
                'index': 0,
                'move_x': -90,
                'move_y': 20,
                'next_con': 10,
                'bottom_keywords': [r'SubTotal:'],
                'bottom_keywords_index': 0,
            },
            'QTY': {
                'x': 80,
                'y': 10,
                'keywords': [r'QTY'],
                'index': 0,
                'move_x': -50,
                'move_y': 20,
                'next_con': 12,
                'bottom_keywords': [r'SubTotal:'],
                'bottom_keywords_index': 0,
            },
            'PRICE': {
                'x': 80,
                'y': 10,
                'keywords': [r'PRICE'],
                'index': 0,
                'move_x': -5,
                'move_y': 20,
                'next_con': 12,
                'bottom_keywords': [r'SubTotal:'],
                'bottom_keywords_index': 0,
            },
            'Invo': {
                'x': 80,
                'y': 10,
                'keywords': [r'Reference'],
                'index': 0,
                'move_x': 60,
                'move_y': -5,
                # 'next_con': 12,
                # 'bottom_keywords': [r'SubTotal:'],
                # 'bottom_keywords_index': 0,
            }
        },
    }
}
